name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry Zksync
        uses: bgd-labs/foundry-zksync-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge build --zksync
        id: build

      - name: Run Forge tests
        run: |
          forge test --mc ZkMinimalAccountTest --via-ir --zksync --system-mode=true
        id: test
